// apps/a-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { ICompany } from '@monroagh/core/model';
import { DateUtils } from '@monroagh/shared';

@Component({
  selector: 'monroagh-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'a-app';

  doSomething() {
    const timestamp = '1551830399000';
    const date = DateUtils.parse(timestamp);
  }

  makeCompany() {
    const c: ICompany = {
      name: 'next company',
      address: {
        addressOne: '',
        addressTwo: '',
        addressThree: '',
        postcode: '',
        country: ''
      },
      users: [
        {
          name: 'Bob', 
          sex: 'yes'
        }
      ]
    }
    console.log(c);
  }
}

<monroagh-nx-welcome></monroagh-nx-welcome>

// apps/r-app/src/app/app.tsx
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import styles from './app.module.scss';
import NxWelcome from './nx-welcome';
import { DateUtils } from '@monroagh/shared';

export function App() {

  
  function doSomething() {
    const timestamp = '1551830399000';
    const date = DateUtils.parse(timestamp);
  }

  return (
    <>
      <NxWelcome title="r-app" />
      <div />
    </>
  );
}

export default App;
